"""empty message

Revision ID: e0a9851a1cc7
Revises: 
Create Date: 2020-07-27 10:54:20.090163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a9851a1cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('tstamp', sa.DateTime(), nullable=True))
    op.add_column('Post', sa.Column('tstamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Post', 'tstamp')
    op.drop_column('Comment', 'tstamp')
    # ### end Alembic commands ###
